spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/commercex
spring.datasource.username=commercex
spring.datasource.password=commercex

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info